spring:
  main:
    banner-mode: "off"
  profiles:
    active: default

  output:
    ansi:
      enabled: always

logging:
  level:
    # Enabling trace for app specific logging.
    com.tvajjala: INFO
    org.springframework: INFO

  batch:
    job:
      enabled: false #disable spring batch jobs by default not working

